drivers: usb: xhci-exynos: Use new link chain quirk API
This fixes the error:
../drivers/usb/host/xhci-exynos.c:771:19: error: implicit declaration of function 'xhci_link_trb_quirk' [-Werror,-Wimplicit-function-declaration]
  771 |         chain_links = !!(xhci_link_trb_quirk(xhci) ||
      |                          ^
../drivers/usb/host/xhci-exynos.c:771:19: note: did you mean 'xhci_link_chain_quirk'?
../drivers/usb/host/xhci.h:2033:20: note: 'xhci_link_chain_quirk' declared here
 2033 | static inline bool xhci_link_chain_quirk(struct xhci_hcd *xhci, enum xhci_ring_type type)
      |                    ^
1 error generated.

Caused by a change in upstream that removed the xhci_link_trb_quirk()
function. Use the new xhci_link_chain_quirk() function instead.

Change-Id: I086b278069af57b73aa768c1dc12bd1b35c83b8c
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>